version: "3"

env:
  BINARY_NAME: "hello"
  GOOS: "linux"
  GOARCH: "amd64"
  CGO_ENABLED: "0"
  VERSION: "beta"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  # Use to build and compress file into the Zip format
  build:
    cmds:
      - go build -o $BINARY_NAME main.go
      - defer: { task: clean }
      - zip lambda-$BINARY_NAME.zip $BINARY_NAME

  upload:lambda:
    cmds:
      - aws s3api put-object --bucket {{.S3_BUCKET_NAME}} --key lambda-$BINARY_NAME.zip --body ./lambda-$BINARY_NAME.zip
    vars:
      S3_BUCKET_NAME:
        sh: aws s3api list-buckets --query 'Buckets[0].Name' --output text

  # Cleaning build result
  clean: rm $BINARY_NAME
